services:
  - type: web
    name: wonderland
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22"
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        value: "d416495193741984"
      - key: CLOUDINARY_API_KEY
        value: "416495193741984"
      - key: CLOUDINARY_API_SECRET
        value: "4mf7TZCqyzog2CsdNzA5d7R9st8"
      - key: NEXT_PUBLIC_API_URL
        value: "https://wonderland-f0vb.onrender.com"
