services:
  - type: web
    name: wonderland
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22"
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        value: "1021477358452-rl84k4sosoogajgttclflj15lltf5is5.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        value: "dyfbk8xc5"
      - key: CLOUDINARY_API_KEY
        value: "263752272783441"
      - key: CLOUDINARY_API_SECRET
        value: "V91inRcRFBQWqbQNF9HzecxEzVw"
      - key: NEXT_PUBLIC_API_URL
        value: "https://wonderland-f0vb.onrender.com"
